{% set version = '1.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geniebpc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/genieBPC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/genieBPC/genieBPC_{{ version }}.tar.gz
  sha256: 876447ff2bae53286aae397f6ce65bd328a4b96775440c67fc2612cfe5568971

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=2.5.0
    - r-dplyr >=1.0.6
    - r-dtplyr >=1.1.0
    - r-httr
    - r-jsonlite
    - r-purrr >=0.3.4
    - r-rlang >=1.0.0
    - r-stringr >=1.4.0
    - r-sunburstr
    - r-tibble >=3.1.2
    - r-tidyr
  run:
    - r-base
    - r-cli >=2.5.0
    - r-dplyr >=1.0.6
    - r-dtplyr >=1.1.0
    - r-httr
    - r-jsonlite
    - r-purrr >=0.3.4
    - r-rlang >=1.0.0
    - r-stringr >=1.4.0
    - r-sunburstr
    - r-tibble >=3.1.2
    - r-tidyr

test:
  commands:
    - $R -e "library('genieBPC')"           # [not win]
    - "\"%R%\" -e \"library('genieBPC')\""  # [win]

about:
  home: https://genie-bpc.github.io/genieBPC/
  license: MIT
  summary: The American Association Research (AACR) Project Genomics Evidence Neoplasia Information
    Exchange (GENIE) BioPharma Collaborative represents a multi-year, multi-institution
    effort to build a pan-cancer repository of linked clinico-genomic data. The genomic
    and clinical data are provided in multiple releases (separate releases for each
    cancer cohort with updates following data corrections), which are stored on the
    data sharing platform 'Synapse' <https://www.synapse.org/>. The 'genieBPC' package
    provides a seamless way to obtain the data corresponding to each release from 'Synapse'
    and to prepare datasets for analysis.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
